
---
version: 2
jobs:
  test:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    steps:
    - checkout
    - run:
        name: Run YAML linting
        command: make lint
    - run:
        name: Validate Cloudformation templates
        command: make validate

  deployApp:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    steps:
    - checkout
    - run:
        name: Install aws-sam-cli
        command: |
          sudo apt update -y
          sudo apt install python3.8 -y 
          sudo apt install python3-pip -y
          sudo pip3 install --no-cache-dir --upgrade aws-sam-cli
    - run:
        name: Run build jwt-authorizer
        command: make localBuild
    - run:
        name: Deploy jwt-authorizer
        command: make deployApp
        no_output_timeout: 20m

workflows:
  version: 2
  build_test_deploy:
    jobs:
    - test
    - deployApp:
        requires:
        - test
        filters:
          branches:
            only: main
          tags:
            ignore: /.*/